# Generated by Django 6.0.4 on 2026-04-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_notification_created_at_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='current_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
