# Generated by Django 6.0.4 on 2026-04-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_current_lat_order_current_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_delivery_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='traffic_factor',
            field=models.FloatField(default=1.0),
        ),
    ]
